In [1]:
import requests 
from dotenv import load_dotenv
import os
import json 
import pandas as pd
from math import e
import yfinance as yf
import pandas as pd

In [8]:
load_dotenv()
td_api_key=os.getenv('td_consumer_key')

In [9]:
ticker=['AAPL']
contractType=['CALL','PUT','ALL']
stdate='2021-09-21'
edate='2021-12-21'
url=f'https://api.tdameritrade.com/v1/marketdata/chains?&symbol={ticker[0]}&contractType={contractType[2]}&fromDate={stdate}&toDate={edate}'
response=requests.get(url, params={'apikey':td_api_key})
data=response.json()

In [10]:
meta={k:v for k, v in data.items() if k in ["symbol","status","underlying","strategy","interval", "isDelayed", "isIndex","interestRate",  "underlyingPrice", "volatility","daysToExpiration","numberOfContracts"]}
meta

{'symbol': 'AAPL',
 'status': 'SUCCESS',
 'underlying': None,
 'strategy': 'SINGLE',
 'interval': 0.0,
 'isDelayed': True,
 'isIndex': False,
 'interestRate': 0.1,
 'underlyingPrice': 143.575,
 'volatility': 29.0,
 'daysToExpiration': 0.0,
 'numberOfContracts': 666}

In [11]:
call=data['callExpDateMap']
dfc=pd.DataFrame.from_dict(call, orient='index').stack().to_frame()
dfc=pd.DataFrame(dfc[0].values.tolist(), index=dfc.index)
dfc=pd.DataFrame(dfc[0].values.tolist(), index=dfc.index)
dfc.head()

                  putCall          symbol                        description  \
2021-09-24:3 75.0    CALL  AAPL_092421C75  AAPL Sep 24 2021 75 Call (Weekly)
             80.0    CALL  AAPL_092421C80  AAPL Sep 24 2021 80 Call (Weekly)
             85.0    CALL  AAPL_092421C85  AAPL Sep 24 2021 85 Call (Weekly)
             90.0    CALL  AAPL_092421C90  AAPL Sep 24 2021 90 Call (Weekly)
             95.0    CALL  AAPL_092421C95  AAPL Sep 24 2021 95 Call (Weekly)

                  exchangeName    bid    ask   last   mark  bidSize  askSize  \
2021-09-24:3 75.0          OPR  68.50  68.65  69.00  68.58       96       60
             80.0          OPR  63.50  63.65  63.81  63.58       63       60
             85.0          OPR  58.50  58.65  58.10  58.58       97       20
             90.0          OPR  53.50  53.65  51.40  53.58      102       20
             95.0          OPR  48.55  48.65  48.75  48.60       20       20

                   ... deliverableNote  isIndexOption  percentChange  \
2021-09-24:3 75.0  ...                           None           1.44
             80.0  ...                           None           1.25
             85.0  ...                           None           0.14
             90.0  ...                           None          -3.06
             95.0  ...                           None           1.51

                   markChange  markPercentChange  intrinsicValue  pennyPilot  \
2021-09-24:3 75.0        0.55               0.81           68.58        True
             80.0        0.55               0.88           63.58        True
             85.0        0.55               0.95           58.58        True
             90.0        0.55               1.04           53.58        True
             95.0        0.58               1.20           48.58        True

                  nonStandard   mini  inTheMoney
2021-09-24:3 75.0       False  False        True
             80.0       False  False        True
             85.0       False  False        True
             90.0       False  False        True
             95.0       False  False        True

[5 rows x 49 columns]

In [12]:
dfc=dfc.reset_index()
dfc.head(3)

,level_0,level_1,putCall,symbol,description,exchangeName,bid,ask,last,mark,...,deliverableNote,isIndexOption,percentChange,markChange,markPercentChange,intrinsicValue,pennyPilot,nonStandard,mini,inTheMoney
0,2021-09-24:3,75.0,CALL,AAPL_092421C75,AAPL Sep 24 2021 75 Call (Weekly),OPR,68.5,68.65,69.00,68.58,...,,None,1.44,0.55,0.81,68.58,True,False,False,True
1,2021-09-24:3,80.0,CALL,AAPL_092421C80,AAPL Sep 24 2021 80 Call (Weekly),OPR,63.5,63.65,63.81,63.58,...,,None,1.25,0.55,0.88,63.58,True,False,False,True
2,2021-09-24:3,85.0,CALL,AAPL_092421C85,AAPL Sep 24 2021 85 Call (Weekly),OPR,58.5,58.65,58.10,58.58,...,,None,0.14,0.55,0.95,58.58,True,False,False,True

In [13]:
set(dfc.level_0)

{'2021-09-24:3',
 '2021-10-01:10',
 '2021-10-08:17',
 '2021-10-15:24',
 '2021-10-22:31',
 '2021-10-29:38',
 '2021-11-19:59',
 '2021-12-17:87'}

In [14]:
put=data['putExpDateMap']
dfp=pd.DataFrame.from_dict(put, orient='index').stack().to_frame()
dfp=pd.DataFrame(dfp[0].values.tolist(), index=dfp.index)
dfp=pd.DataFrame(dfp[0].values.tolist(), index=dfp.index)
dfp.reset_index(inplace=True)
dfp.head()

,level_0,level_1,putCall,symbol,description,exchangeName,bid,ask,last,mark,...,deliverableNote,isIndexOption,percentChange,markChange,markPercentChange,intrinsicValue,pennyPilot,nonStandard,mini,inTheMoney
0,2021-09-24:3,75.0,PUT,AAPL_092421P75,AAPL Sep 24 2021 75 Put (Weekly),OPR,0.0,0.01,0.01,0.01,...,,None,9900.00,0.0,4900.00,-68.58,True,False,False,False
1,2021-09-24:3,80.0,PUT,AAPL_092421P80,AAPL Sep 24 2021 80 Put (Weekly),OPR,0.0,0.01,0.01,0.01,...,,None,4900.00,0.0,2400.00,-63.58,True,False,False,False
2,2021-09-24:3,85.0,PUT,AAPL_092421P85,AAPL Sep 24 2021 85 Put (Weekly),OPR,0.0,0.01,0.01,0.01,...,,None,1900.00,0.0,900.00,-58.58,True,False,False,False
3,2021-09-24:3,90.0,PUT,AAPL_092421P90,AAPL Sep 24 2021 90 Put (Weekly),OPR,0.0,0.01,0.01,0.01,...,,None,809.09,0.0,354.55,-53.58,True,False,False,False
4,2021-09-24:3,95.0,PUT,AAPL_092421P95,AAPL Sep 24 2021 95 Put (Weekly),OPR,0.0,0.01,0.01,0.01,...,,None,316.67,0.0,108.33,-48.58,True,False,False,False

In [15]:
dfc.shape

(333, 51)

In [16]:
dfp.shape

(333, 51)

In [17]:
df_all=pd.concat([dfc, dfp])
df_all.shape

(666, 51)

In [18]:
df_all['strike_price']=df_all['level_1']
df_all['strike_price']=df_all['strike_price'].astype('float64')

In [19]:
df_all['volatility']=df_all['volatility'].astype('float64')
df_all['delta']=df_all['delta'].astype('float64')
df_all['gamma']=df_all['gamma'].astype('float64')
df_all['theta']=df_all['theta'].astype('float64')

In [20]:
# Create 3 new dataframes: 
#      ‘inTheMoney’ = False & ‘daysToExpiration’ between 15 & 30. (=df1)
#.     ‘inTheMoney’ = False & ‘daysToExpiration’ between 31 & 60. (=df2)
#      ‘inTheMoney’ = False & ‘daysToExpiration’ between 61 & 90. (=df3)
df1=df_all.loc[(df_all.inTheMoney==False) & (df_all.daysToExpiration>=15) & (df_all.daysToExpiration<=30)]
df2=df_all.loc[(df_all.inTheMoney==False) & (df_all.daysToExpiration>=31) & (df_all.daysToExpiration<=60)]
df3=df_all.loc[(df_all.inTheMoney==False) & (df_all.daysToExpiration>=61) & (df_all.daysToExpiration<=90)]

In [ ]:
!pip install yfinance

In [22]:
AAPL=yf.download('AAPL')
AAPL

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100600,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095352,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088353,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090540,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.093165,73449600
...,...,...,...,...,...,...
2021-09-15,148.559998,149.440002,146.369995,149.029999,149.029999,83281300
2021-09-16,148.440002,148.970001,147.220001,148.789993,148.789993,68034100
2021-09-17,148.820007,148.820007,145.759995,146.059998,146.059998,129728700
2021-09-20,143.800003,144.839996,141.270004,142.940002,142.940002,123304600
2021-09-21,143.929993,144.600006,142.779999,143.569000,143.569000,33443778

In [23]:
# Check for underlying price (closing Price) for last 6 days = [ p0, p1,p2,p3,p4, p5)
df_aapl=AAPL.iloc[-6:]
df_aapl=df_aapl[['Adj Close']]
df_aapl

             Adj Close
Date
2021-09-14  148.119995
2021-09-15  149.029999
2021-09-16  148.789993
2021-09-17  146.059998
2021-09-20  142.940002
2021-09-21  143.569000

In [24]:
# Calculate the daily changes in price of Underlying P = Change in P = todays price - yesterday’s price =Pn - P(n-1)
df_aapl2=df_aapl.diff()
df_aapl2.dropna(inplace=True)

In [25]:
df_aapl2

            Adj Close
Date
2021-09-15   0.910004
2021-09-16  -0.240005
2021-09-17  -2.729996
2021-09-20  -3.119995
2021-09-21   0.628998

In [26]:
import numpy as np
# Square the daily changes in the price as per step 1
# Calculate 5 days average of the squared daily changes in Price as per step 2 for 5 trailing days = S
df_aapl2['new']=df_aapl2['Adj Close']**2/len(df_aapl2)
df_aapl2


# Calculate the square root of average, S as per step 3 = DVIV
DVIV=np.sqrt(df_aapl2['new'].sum())

In [27]:
# Vt = Theoretical volatility
vt=df_all[['theoreticalVolatility']]

In [28]:
!pip install pysimplegui

Requirement already satisfied: pysimplegui in c:\programdata\anaconda3\lib\site-packages (4.47.0)

In [29]:
import PySimpleGUI as sg

In [30]:
user_input=pd.DataFrame()

In [ ]:
layout = [
    [sg.Text('Please fill out the following fields:')],
    
    [sg.Text('Investment Duration', size=(17,1)), sg.Combo(['Short-Term', 'Mid Term', 'Long Term','All']
, key='Investment Duration')],   
    [sg.Submit(), sg.Button('Clear'), sg.Exit()]
]

window = sg.Window('Data Entry to determine Investment Strategy', layout)

def clear_input():
    for key in values:
        window[key]('')
    return None

while True:
    event, values = window.read()
    if event == sg.WIN_CLOSED or event == 'Exit':
        break
    if event == 'Clear':
        clear_input()
    if event == 'Submit':
        user_input = user_input.append(values, ignore_index=True)
        sg.popup('Thanks for feedback!')
        clear_input()
window.close()

In [ ]:
# user_input['Investment Duration'].values[0]=='Short Term'

In [ ]:
if user_input.iloc[0,0]=='Long Term':
    df_sub=df3
elif user_input.iloc[0,0]=='Mid Term':
    df_sub=df2
elif user_input.iloc[0,0]=='Short-Term':
    df_sub=df1
else:
    df_sub=df_all

In [ ]:
HPD= 3
ECIV = np.sqrt(DVIV * ((HPD)* 5/7))
# Vega Effect, VE =  -ABS(Ve) * ECIV
df_sub['vega_effect']=df_sub['vega'].abs()*(-1)*ECIV
# Theta Effect, TE = Th * HPD
df_sub['Theta Effect']= df_sub['theta'] * HPD
most_recent_apple_price=df_aapl.iloc[-1]
IV=df_sub['volatility']
# Expected Price Change, EPC = P * (Exp (IV*((HPD/365) ^ 0.5))-1)
#EPC = P * (e**(IV*((HPD/365)**0.5)) - 1)
df_sub['Expected_price_change']= most_recent_apple_price.values[0]*(e**(IV.values*(HPD/365)**0.5)-1)
# Delta Effect (DE) = -ABS(Delta)* EPC
df_sub['Delta_Effect']=abs(-df_sub['delta'])*(-1)*df_sub['Expected_price_change']
# Gamma Effect (GE) = Gamma * (EPC^2)/2
df_sub['gamma_effect']=df_sub['gamma']*(df_sub['Expected_price_change']**2)/2
# VTRRR = (VE/TE)
VTRRR=df_sub['vega_effect']/df_sub['Theta Effect']
# DTRRR = (DE +GE)/TE
DTRRR=(df_sub['Delta_Effect']+df_sub['gamma_effect'])/df_sub['Theta Effect']
# Rt = DTRRR +VTRRR  risk return ratio
# Add a column Risk Return Ratio
df_sub['Risk_Return']=DTRRR +VTRRR 
#For ‘putCall’ = CALL & ` strike price in the range, (‘p0 + 0.75 * Vt’  to p0 + 1.25 *Vt),

In [ ]:
# put_long

In [ ]:
#Rt = Rt min & Symbol_CS = corresponding symbol. Dcs = Delta, Pcs = Strike Price
# For ‘putCall’ = CALL & ` strike price in the range, (‘Pcs + 15’ to Pcs + 35),
# Rt = Rt min & Symbol_CL= corresponding symbol. Dcl = Delta, Pcl = Strike Price

call=df_sub.loc[(df_sub.putCall=='CALL')& 
           (df_sub.strike_price.values >=most_recent_apple_price[0]+0.75*vt.iloc[0,0])& 
           (df_sub.strike_price.values <=most_recent_apple_price[0]+1.25*vt.iloc[0,0])]
call_short=call.loc[call['Risk_Return']==call['Risk_Return'].min()][['symbol','delta','strike_price','Risk_Return','ask','bid']]
#For ‘putCall’ = CALL & ` strike price in the range, (‘Pcs + 15’ to Pcs + 35),
#Rt = Rt min & Symbol_CL= corresponding symbol. Dcl = Delta, Pcl = Strike Price

pcs=call_short['strike_price']
call_long=df_sub.loc[(df_sub.putCall=='CALL')& 
           (df_sub.strike_price.values >=pcs.values[0]+15)& 
           (df_sub.strike_price.values <=pcs.values[0]+35)
                    ]
call_long= call_long.loc[call_long['Risk_Return']==call_long['Risk_Return'].min()][['symbol','delta','strike_price','Risk_Return','ask','bid']]
# For ‘putCall’ = PUT & ` strike price < (‘p0 – (Pcs-P0)* 1.25)
# Delta_diff = [Abs(Delta – Dcs)]
# Check for min Delta_diff
# Dps = corresponding Delta, Symbol_PS = corresponding symbol Pps = Strike Price
put_short= df_sub.loc[(df_sub.putCall=='PUT')& 
           (df_sub.strike_price.values < (most_recent_apple_price.iloc[0]-(pcs.iloc[0]-most_recent_apple_price.iloc[0])*1.25))
                    ]
put_short['delta_diff']= abs(put_short['delta']-call_short.delta.iloc[0])
put_short= put_short.loc[put_short['delta_diff']==put_short['delta_diff'].min()][['symbol','delta','strike_price','Risk_Return','ask','bid']]
put_short=put_short.loc[put_short.strike_price==put_short.strike_price.max()]
# For ‘putCall’ = PUT & ` strike price <  (‘Pps – (Pcl-Pcs)*1.25)
# Delta_diff = [Abs(Delta – Dcl)]
# Check for min Delta_diff 
# Dpl = corresponding Delta, Symbol_PL = corresponding symbol

pps=put_short['strike_price']
put_long=df_sub.loc[(df_sub.putCall=='PUT')& 
                    (df_sub.strike_price.values <= (pps.iloc[0]-(call_long.strike_price.iloc[0]-call_short.strike_price.iloc[0])*1) )
                    ]

put_long['delta_diff']= abs(put_long['delta']-call_long.iloc[0,1])
put_long= put_long.loc[put_long['delta_diff']==put_long['delta_diff'].min()][['symbol','delta','strike_price','Risk_Return','ask','bid']]
put_long=put_long.loc[put_long.strike_price==put_long.strike_price.max()]

In [ ]:

# Max Income, I = Price of CS + Price of PS – Price of CL -Price of PL
# Maximum Loss, Pot_Loss = Max[( Pps- Ppl), (Pcl-Pcs)]-I
# Break Even Lower be_lower= Pps- I
# Break Even Upper, be_upper= Pcs + I
max_income=(call_short.ask.values[0]+ put_short.ask.values[0]-call_long.ask.values[0]-put_long.ask.values[0])*100
max_loss= max((put_short.strike_price.values[0]-put_long.strike_price.values[0]),
              (call_long.strike_price.values[0]-call_short.strike_price.values[0]))-max_income
break_even_lower= put_short.strike_price.values[0]-max_income
break_even_upper= call_short.strike_price.values[0]+max_income
# Recommendations:
# Call Short: Symbol_CS
# Call Long: Symbol_CL
# Put Short: Symbol_PS
# Put Long: Symbol_PL
# Maximum Possible Profit = I
# Maximum Potential Loss = Potential_Loss
# Profitable Price Range = ( be_lower, be_upper)
print(f'Call Short:     {call_short.symbol.values}')
print(f'Call Long:      {call_long.symbol.values}')
print(f'Put Short:      {put_short.symbol.values}')
print(f'Put Long:       {put_long.symbol.values}')

print(f'Maximum Possible Profit:      {max_income}')
print(f'Maximum Potential loss:      {max_loss}')

print(f'Break Even Lower be_lower:      {break_even_lower}')
print(f'Break Even Upper:               {break_even_upper}')

In [ ]:
# Visualizations: